name: Build and Push Docker Image to Alibaba Cloud ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Alibaba Cloud ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }}
          username: ${{ secrets.ALIYUN_REGISTRY_USER }}
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ALIYUN_REGISTRY }}/naruto007/sais_medicine_narut:latest .
      - name: Debug Docker Push
        run: |
          echo "→ Pushing image to ${{ secrets.ALIYUN_REGISTRY }}/naruto007/sais_medicine_narut:latest"
          docker push "${{ secrets.ALIYUN_REGISTRY }}/naruto007/sais_medicine_narut:latest" --verbose || true
          echo; echo "Local images:" && docker images
      - name: Push Docker image
        run: |
          docker push ${{ secrets.ALIYUN_REGISTRY }}/naruto007/sais_medicine_narut:latest
